apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: workshop-operator
  template:
    metadata:
      labels:
        name: workshop-operator
    spec:
      serviceAccountName: workshop-operator
      containers:
        - name: operator
          # Replace this with the built image name
          image: "{{ OPERATOR_IMAGE_PATH }}"
          imagePullPolicy: "Always"
          volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "workshop-operator"
      volumes:
        - name: runner
          emptyDir: {}
